### ISSUE TITLE
Import of `ensmallen` fails due to missing imports

### ISSUE THREAD

**Issue by caufieldjh** [AnacletoLAB/ensmallen#192]
Some (or all?) dependencies aren't getting installed by pip.

Example:
The `cpuinfo` module may not get installed by pip, but it's imported in [the `__init__.py`](https://github.com/AnacletoLAB/ensmallen/blob/master/bindings/python/ensmallen/__init__.py).
On a fresh pip install (from grape) and venv:
```
>>> from ensmallen import Graph
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/harry/test85812/lib/python3.8/site-packages/ensmallen/__init__.py", line 8, in <module>
    import cpuinfo
ModuleNotFoundError: No module named 'cpuinfo'
```

I see `py-cpuinfo` is in the Cargo.toml, and if I install it with pip then this solves the problem, _but..._
then I get a ModuleNotFoundError for `bioregistry`. 
Same for `downloaders`.

Ensmallen is `0.8.35`.

**Comment by LucaCappelletti94** [comment]
We have just updated the build using the newer maturin version, possibly it has some issues. I will look into it.

**Comment by LucaCappelletti94** [comment]
The issue continues to be present ensmallen-wise. I have patched it by adding the requirements to grape.
