### ISSUE TITLE
KGCOVID19 fails to load

### ISSUE THREAD

**Issue by airbender-1** [AnacletoLAB/ensmallen#232]
KGCOVID19 fails to load when loading from "grape" library.

```python
from grape.datasets.kghub import KGCOVID19
kgcovid19 = KGCOVID19()
```

ValueError: Request to url https://kg-hub.berkeleybop.io/kg-covid-19/current/kg-covid-19.tar.gz finished with status code 403.

Full trace:

> Traceback (most recent call last):                                                             
  File "/Users/x/code/grape-testing/.venv/lib/python3.9/site-packages/ensmallen/datasets/graph_retrieval.py", line 350, in download
    self._downloader.download(
  File "/Users/x/code/grape-testing/.venv/lib/python3.9/site-packages/downloaders/downloaders/base_downloader.py", line 315, in download
    report = pd.DataFrame([
  File "/Users/x/code/grape-testing/.venv/lib/python3.9/site-packages/downloaders/downloaders/base_downloader.py", line 316, in <listcomp>
    self._download_wrapper(task)
  File "/Users/x/code/grape-testing/.venv/lib/python3.9/site-packages/downloaders/downloaders/base_downloader.py", line 262, in _download_wrapper
    return self._download(**kwargs)
  File "/Users/x/code/grape-testing/.venv/lib/python3.9/site-packages/downloaders/downloaders/base_downloader.py", line 241, in _download
    raise download_crash_exception
  File "/Users/x/code/grape-testing/.venv/lib/python3.9/site-packages/downloaders/downloaders/base_downloader.py", line 234, in _download
    raise process_exception
  File "/Users/x/code/grape-testing/.venv/lib/python3.9/site-packages/downloaders/downloaders/base_downloader.py", line 195, in _download
    raise ValueError(
ValueError: Request to url https://kg-hub.berkeleybop.io/kg-covid-19/current/kg-covid-19.tar.gz finished with status code 403.

My environment:

Mac M2
Python 3.9
venv

**Comment by LucaCappelletti94** [comment]
Hi, this is not an Ensmallen issue but a kg-hub issue - apparently, their "current" KGCOVID19 version is not available at this time, as it is giving a 403 error. Consider using another version.

**Comment by caufieldjh** [comment]
That's my doing - we started seeing unexpected levels of downloads on KG-Hub, including with KG-COVID-19, so we made some graph files temporarily private. @airbender-1, please send an email to me (jhc@lbl.gov) to get a copy of the graph file for now
